# Generated by Django 6.1.1 on 2026-10-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudiantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=150)),
                ('numero_cuatrimestres', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'planes estudiantiles',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuatrimestre', models.PositiveSmallIntegerField()),
                ('es_tronco_comun', models.BooleanField(default=False)),
                ('plan_estudiantil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='catalogo.planestudiantil')),
            ],
        ),
    ]
