# Generated by Django 6.1.1 on 2026-10-03 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asesorias', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesorias_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesormateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesores', to='catalogo.materia'),
        ),
        migrations.AddField(
            model_name='asesormateria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asesoradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='asesor_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesorias', to='asesorias.asesormateria'),
        ),
        migrations.AddField(
            model_name='resenia',
            name='asesoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resenia', to='asesorias.asesoria'),
        ),
        migrations.AddField(
            model_name='skillasesor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='asesormateria',
            constraint=models.UniqueConstraint(fields=('usuario', 'materia'), name='uniq_asesor_materia'),
        ),
    ]
